spring.application.name=ecommerce

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

## PostgreSQL JDBC driver class (optional, auto-detected in newer Spring Boot versions)
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Set SQL dialect explicitly (optional but helps avoid dialect mismatches)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
